dependencies:
- name: nginx-ingress
  version: 1.41.2
  repository: https://kubernetes-charts.storage.googleapis.com
- name: mysql
  version: 1.6.7
  repository: https://kubernetes-charts.storage.googleapis.com